name: buildgem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.144.0
      with:
        ruby-version: 2.7
        bundler-cache: true
        
    - name: Run Specs
      run: |
        bundle exec rspec
